// Generates ios/Flutter/Env.xcconfig from .env.
//
// Most configuration reaches the app through the bundled .env asset at
// runtime. The AdMob application ID cannot: it has to be in Info.plist, which
// is assembled long before any Dart runs. Android solves this by parsing .env
// in build.gradle.kts at configuration time. Xcode has no equivalent hook, so
// this script bridges the gap.
//
// Run it after changing any ADMOB_APP_ID_* value:
//
//     dart run tool/sync_env.dart
//
// The generated file is gitignored. `ios/Flutter/EnvDefaults.xcconfig` holds
// tracked fallbacks, and the generated file is included after it so its values
// win when present.

import 'dart:io';

/// Keys copied from .env into the xcconfig.
///
/// Kept explicit rather than copying everything: an xcconfig is not a secret
/// store, and values with characters Xcode treats specially (a `//` inside a
/// URL, for instance) would silently truncate.
const List<String> _exportedKeys = ['ADMOB_APP_ID_IOS'];

const String _envPath = '.env';
const String _outputPath = 'ios/Flutter/Env.xcconfig';

void main(List<String> args) {
  final envFile = File(_envPath);
  if (!envFile.existsSync()) {
    stderr.writeln(
      'No $_envPath found. Copy .env.example to .env first:\n'
      '\n'
      '    cp .env.example .env\n',
    );
    exit(1);
  }

  final values = _parseEnv(envFile.readAsLinesSync());
  final buffer = StringBuffer()
    ..writeln('// Generated by tool/sync_env.dart. Do not edit.')
    ..writeln('// Run `dart run tool/sync_env.dart` after changing .env.')
    ..writeln();

  var written = 0;
  for (final key in _exportedKeys) {
    final value = values[key];
    if (value == null || value.isEmpty) continue;

    if (value.contains('//')) {
      stderr.writeln(
        'Skipping $key: an xcconfig value cannot contain "//", '
        'which Xcode reads as the start of a comment.',
      );
      continue;
    }

    buffer.writeln('$key = $value');
    written++;
  }

  final output = File(_outputPath);
  output.parent.createSync(recursive: true);
  output.writeAsStringSync(buffer.toString());

  stdout.writeln('Wrote $_outputPath ($written key(s)).');
}

/// Parses a `key=value` file.
///
/// Splits on the first `=` and nothing else, which is what a .env file
/// actually means. Anything fancier mangles values containing `:` or `\`.
Map<String, String> _parseEnv(List<String> lines) {
  final result = <String, String>{};

  for (final raw in lines) {
    final line = raw.trim();
    if (line.isEmpty || line.startsWith('#')) continue;

    final index = line.indexOf('=');
    if (index <= 0) continue;

    final key = line.substring(0, index).trim();
    var value = line.substring(index + 1).trim();

    // Strip a single layer of surrounding quotes, which people add out of
    // habit and which would otherwise end up inside the xcconfig value.
    if (value.length >= 2 &&
        ((value.startsWith('"') && value.endsWith('"')) ||
            (value.startsWith("'") && value.endsWith("'")))) {
      value = value.substring(1, value.length - 1);
    }

    result[key] = value;
  }

  return result;
}
